import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<html lang='en'>
				<head>
					<Script
						strategy='beforeInteractive'
						src='https://telegram.org/js/telegram-web-app.js'
					/>
				</head>
				<body className={inter.className}>
					<div className='pb-6 pt-6'>{children}</div>
				</body>
			</html>
		</>
	)
}
